package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"eventix/gateway/graph/model"
	authPb "eventix/proto/auth/pb"
	catalogPb "eventix/proto/catalog/pb"
	"time"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	grpcReq := authPb.RegisterRequest{
		Email:    input.Email,
		Password: input.Password,
		Name:     input.Name,
	}

	grpcResp, err := r.Clients.Auth.Register(ctx, &grpcReq)
	if err != nil {
		return nil, handleGRPCError(err)
	}

	expiresIn := int32(grpcResp.ExpiresIn)
	return &model.AuthPayload{
		UserID:       grpcResp.UserId,
		AccessToken:  grpcResp.AccessToken,
		RefreshToken: grpcResp.RefreshToken,
		ExpiresIn:    expiresIn,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	grpcReq := authPb.LoginRequest{
		Email:    input.Email,
		Password: input.Password,
	}

	grpcResp, err := r.Clients.Auth.Login(ctx, &grpcReq)
	if err != nil {
		return nil, handleGRPCError(err)
	}

	expiresIn := int32(grpcResp.ExpiresIn)
	return &model.AuthPayload{
		UserID:       grpcResp.UserId,
		AccessToken:  grpcResp.AccessToken,
		RefreshToken: grpcResp.RefreshToken,
		ExpiresIn:    expiresIn,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, refreshToken string) (bool, error) {
	grpcReq := authPb.LogoutRequest{
		RefreshToken: refreshToken,
	}

	grpcResp, err := r.Clients.Auth.Logout(ctx, &grpcReq)
	if err != nil {
		return false, handleGRPCError(err)
	}

	return grpcResp.Success, nil
}

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input model.CreateEventInput) (*model.Event, error) {
	grpcReq := catalogPb.CreateEventRequest{
		Title:       input.Title,
		Description: *input.Description,
		Venue:       input.Venue,
		EventDate:   input.EventDate.Format(time.RFC3339),
		TotalSeats:  input.TotalSeats,
		Price:       input.Price,
	}

	grpcResp, err := r.Clients.Catalog.CreateEvent(ctx, &grpcReq)
	if err != nil {
		return nil, handleGRPCError(err)
	}

	parseDate, err := time.Parse(time.RFC3339, grpcResp.Event.EventDate)
	if err != nil {
		return nil, handleGRPCError(err)
	}

	return &model.Event{
		ID:             grpcResp.Event.Id,
		Title:          grpcResp.Event.Title,
		Description:    &grpcResp.Event.Description,
		Venue:          grpcResp.Event.Venue,
		EventDate:      parseDate,
		TotalSeats:     grpcResp.Event.TotalSeats,
		AvailableSeats: grpcResp.Event.AvailableSeats,
		Price:          grpcResp.Event.Price,
	}, nil
}

// UpdateEvent is the resolver for the updateEvent field.
func (r *mutationResolver) UpdateEvent(ctx context.Context, id string, input model.UpdateEventInput) (*model.Event, error) {
	cur, err := r.Clients.Catalog.GetEvent(ctx, &catalogPb.GetEventRequest{EventId: id})
	if err != nil {
		return nil, handleGRPCError(err)
	}

	grpcReq := catalogPb.UpdateEventRequest{
		EventId:     id,
		Title:       cur.Event.Title,
		Description: cur.Event.Description,
		Venue:       cur.Event.Venue,
		EventDate:   cur.Event.EventDate,
		TotalSeats:  cur.Event.TotalSeats,
		Price:       cur.Event.Price,
	}

	for _, field := range input.UpdateMask {
		switch field {
		case "title":
			if input.Title != nil {
				grpcReq.Title = *input.Title
			}
		case "description":
			if input.Description != nil {
				grpcReq.Description = *input.Description
			}
		case "venue":
			if input.Venue != nil {
				grpcReq.Venue = *input.Venue
			}
		case "eventDate":
			if input.EventDate != nil {
				grpcReq.EventDate = input.EventDate.String()
			}
		case "totalSeats":
			if input.TotalSeats != nil {
				grpcReq.TotalSeats = int32(*input.TotalSeats)
			}
		case "price":
			if input.Price != nil {
				grpcReq.Price = *input.Price
			}
		}
	}

	grpcResp, err := r.Clients.Catalog.UpdateEvent(ctx, &grpcReq)
	if err != nil {
		return nil, handleGRPCError(err)
	}

	parseDate, err := time.Parse(time.RFC3339, grpcResp.Event.EventDate)
	if err != nil {
		return nil, handleGRPCError(err)
	}

	return &model.Event{
		ID:             grpcResp.Event.Id,
		Title:          grpcResp.Event.Title,
		Description:    &grpcResp.Event.Description,
		Venue:          grpcResp.Event.Venue,
		EventDate:      parseDate,
		TotalSeats:     grpcResp.Event.TotalSeats,
		AvailableSeats: grpcResp.Event.AvailableSeats,
		Price:          grpcResp.Event.Price,
	}, nil
}

// DeleteEvent is the resolver for the deleteEvent field.
func (r *mutationResolver) DeleteEvent(ctx context.Context, id string) (bool, error) {
	grpcReq := catalogPb.DeleteEventRequest{
		EventId: id,
	}

	grpcResp, err := r.Clients.Catalog.DeleteEvent(ctx, &grpcReq)
	if err != nil {
		return false, handleGRPCError(err)
	}

	return grpcResp.Success, nil
}

// GetEvent is the resolver for the getEvent field.
func (r *queryResolver) GetEvent(ctx context.Context, id string) (*model.Event, error) {
	grpcReq := catalogPb.GetEventRequest{
		EventId: id,
	}

	grpcResp, err := r.Clients.Catalog.GetEvent(ctx, &grpcReq)
	if err != nil {
		return nil, handleGRPCError(err)
	}

	parseDate, err := time.Parse(time.RFC3339, grpcResp.Event.EventDate)
	if err != nil {
		return nil, handleGRPCError(err)
	}

	return &model.Event{
		ID:             grpcResp.Event.Id,
		Title:          grpcResp.Event.Title,
		Description:    &grpcResp.Event.Description,
		Venue:          grpcResp.Event.Venue,
		EventDate:      parseDate,
		TotalSeats:     grpcResp.Event.TotalSeats,
		AvailableSeats: grpcResp.Event.AvailableSeats,
		Price:          grpcResp.Event.Price,
	}, nil
}

// ListEvents is the resolver for the listEvents field.
func (r *queryResolver) ListEvents(ctx context.Context, input model.ListEventsInput) (*model.EventList, error) {
	grpcReq := catalogPb.ListEventsRequest{
		Page:        input.Page,
		PageSize:    input.PageSize,
		SearchQuery: *input.SearchQuery,
	}

	grpcResp, err := r.Clients.Catalog.ListEvents(ctx, &grpcReq)
	if err != nil {
		return nil, handleGRPCError(err)
	}

	events := make([]*model.Event, len(grpcResp.Events))
	for i, event := range grpcResp.Events {
		parseDate, err := time.Parse(time.RFC3339, event.EventDate)
		if err != nil {
			return nil, handleGRPCError(err)
		}
		events[i] = &model.Event{
			ID:             event.Id,
			Title:          event.Title,
			Description:    &event.Description,
			Venue:          event.Venue,
			EventDate:      parseDate,
			TotalSeats:     event.TotalSeats,
			AvailableSeats: event.AvailableSeats,
			Price:          event.Price,
		}
	}

	return &model.EventList{
		Events:     events,
		TotalCount: grpcResp.TotalCount,
		Page:       grpcResp.Page,
		PageSize:   grpcResp.PageSize,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
