// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AuthPayload struct {
	UserID       string `json:"userId"`
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int32  `json:"expiresIn"`
}

type CreateEventInput struct {
	Title       string    `json:"title"`
	Description *string   `json:"description,omitempty"`
	Venue       string    `json:"venue"`
	EventDate   time.Time `json:"eventDate"`
	TotalSeats  int32     `json:"totalSeats"`
	Price       float64   `json:"price"`
}

type Event struct {
	ID             string     `json:"id"`
	Title          string     `json:"title"`
	Description    *string    `json:"description,omitempty"`
	Venue          string     `json:"venue"`
	EventDate      time.Time  `json:"eventDate"`
	TotalSeats     int32      `json:"totalSeats"`
	AvailableSeats int32      `json:"availableSeats"`
	Price          float64    `json:"price"`
	CreatedAt      *time.Time `json:"createdAt,omitempty"`
	UpdatedAt      *time.Time `json:"updatedAt,omitempty"`
}

type EventList struct {
	Events     []*Event `json:"events"`
	TotalCount int32    `json:"totalCount"`
	Page       int32    `json:"page"`
	PageSize   int32    `json:"pageSize"`
}

type ListEventsInput struct {
	Page        int32   `json:"page"`
	PageSize    int32   `json:"pageSize"`
	SearchQuery *string `json:"searchQuery,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type UpdateEventInput struct {
	Title       *string      `json:"title,omitempty"`
	Description *string      `json:"description,omitempty"`
	Venue       *string      `json:"venue,omitempty"`
	EventDate   *time.Time   `json:"eventDate,omitempty"`
	TotalSeats  *int32       `json:"totalSeats,omitempty"`
	Price       *float64     `json:"price,omitempty"`
	UpdateMask  []EventField `json:"updateMask,omitempty"`
}

type EventField string

const (
	EventFieldTitle       EventField = "title"
	EventFieldDescription EventField = "description"
	EventFieldVenue       EventField = "venue"
	EventFieldEventDate   EventField = "eventDate"
	EventFieldTotalSeats  EventField = "totalSeats"
	EventFieldPrice       EventField = "price"
)

var AllEventField = []EventField{
	EventFieldTitle,
	EventFieldDescription,
	EventFieldVenue,
	EventFieldEventDate,
	EventFieldTotalSeats,
	EventFieldPrice,
}

func (e EventField) IsValid() bool {
	switch e {
	case EventFieldTitle, EventFieldDescription, EventFieldVenue, EventFieldEventDate, EventFieldTotalSeats, EventFieldPrice:
		return true
	}
	return false
}

func (e EventField) String() string {
	return string(e)
}

func (e *EventField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventField", str)
	}
	return nil
}

func (e EventField) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EventField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EventField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
